
//#ifndef PROCESS_INFO_H  // these lines generated by AI, probalby not needed, kept just in case.
//#define PROCESS_INFO_H

struct processInfo
{
int state; // process state
int ppid; // parent PID
int sz; // size of process memory, in bytes
int nfd; // number of open file descriptors in the process
int nrswitch; // number context switches in
};
